FIxing HTTP 406 error while runing the test suite (npm test)
wikimedia/html-metadata pull request #96
Opened 2024-07-11 15:23 UTC by Jacobojijo

This is to fix issue #95 

## Solution

I modified the `scraping.js` file to use more browser-like User-Agent and Accept headers. Here are the key changes:

1. Added constants for user agent and accept header:

   ```javascript
   const userAgent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36';
   const acceptHeader = 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8';
   
 * Created a `getWithHeaders` function to make requests with these headers:

    ```javascript
    function getWithHeaders(url) {
        return preq.get({
            uri: url,
            headers: {
                'User-Agent': userAgent,
                'Accept': acceptHeader
            }
        });
    }
    ```

* Updated all `preq.get()` calls to use `getWithHeaders()` instead.

* Modified the `meta()` function calls to include the headers:

    ```javascript
    return meta({
        uri: url,
        headers: {
            'User-Agent': userAgent,
            'Accept': acceptHeader
        }
    })
    ```
 This should improve the reliability of the test suite, especially when dealing with websites that have stricter requirements for incoming requests.

2024-07-11 19:31 UTC, mvolz commented on package.json
> +     "nock": "^13.3.0"
extra space here

2024-07-11 19:37 UTC, mvolz commented on test/scraping.js
> -	});
Stick to tabs please. (Probably this repo needs some linting added!)

2024-07-11 19:38 UTC, mvolz requested changes
Just some style stuff (we should add linting so that's automated, sorry!)

2024-07-17 08:26 UTC, Jacobojijo commented
Hello @mvolz would you please do the PR review for the changes made ?

2024-07-17 17:59 UTC, mvolz requested changes

2024-07-17 17:59 UTC, mvolz commented on package.json
> +}
The red circle with the line through it means this file is missing a new line character. 
https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

2024-07-18 11:17 UTC, Jacobojijo commented
@mvolz, can you review my PR? I also think a styling lint should be added to help in other future changes. I'm thinking of introducing one to this project. What do you think?

2024-07-18 13:06 UTC, Jacobojijo commented
@mvolz, I guess this PR is done

2024-07-18 15:12 UTC, closed without merging